window.EXC = window.EXC || {};
window.EXC.recycle = [
["Aluminum cans","Kitchen","soda can, drink can, beer can","Aluminum can be recycled forever without losing quality. A can you recycle today could be back on the shelf in about two months.",["Rinse out any leftover drink.","Leave it whole or gently squash it to save space.","Pop it in your household recycling bin."]],
["Steel food cans","Kitchen","tin can, soup can, bean can","Steel cans are magnetic, which makes them easy for recycling centers to sort.",["Scrape out food and give it a quick rinse.","Push the lid inside the can so nobody gets cut.","Put it in your recycling bin."]],
["Glass bottles","Kitchen","wine bottle, beer bottle, sauce bottle","Glass can be melted down and remade again and again.",["Rinse out the bottle.","Remove metal or plastic caps and recycle those separately.","Take to a bottle bank or put in your glass recycling."]],
["Glass jars","Kitchen","jam jar, pickle jar","Jars recycle just like bottles.",["Scrape out food and rinse.","Take the lid off. Metal lids can usually go in with cans.","Put in the glass recycling."]],
["Plastic drink bottles","Kitchen","pet bottle, water bottle, soda bottle","Clear plastic bottles are among the most recycled plastics and can become new bottles or clothing.",["Empty and quickly rinse.","Squash it and put the cap back on, as most places now accept caps attached.","Pop it in your recycling bin."]],
["Milk jugs","Kitchen","hdpe, milk bottle, plastic jug","Milk jugs are made from a sturdy plastic that recycles well.",["Rinse out the milk so it doesn't smell.","Squash it flat.","Recycle with your household plastics."]],
["Cardboard boxes","Home","box, carton, delivery box","Cardboard is one of the easiest materials to recycle.",["Remove plastic tape and packing materials.","Flatten the box.","Put in your paper and cardboard recycling, keeping it dry."]],
["Pizza boxes","Kitchen","pizza box","Pizza boxes can be recycled, but grease is the problem.",["Tear off the clean lid and recycle it.","Put greasy parts in compost or food waste if your area allows.","Otherwise put greasy bits in the general bin."]],
["Newspapers","School & Office","newspaper, newsprint","Newspapers can be turned into new paper up to seven times.",["Keep them dry.","Remove any plastic wrapping.","Put in your paper recycling."]],
["Magazines","School & Office","catalog, glossy magazine","Glossy magazines are recyclable too.",["Remove plastic wrappers and free gifts.","Staples can usually stay in.","Put in paper recycling."]],
["Office paper","School & Office","printer paper, a4, copy paper","Clean office paper is high quality and easy to recycle.",["Remove paper clips and plastic sleeves.","Keep it flat and dry.","Recycle with paper."]],
["Shredded paper","School & Office","shredded documents","Shredded paper is tricky because the pieces are small.",["Check if your area accepts it in paper recycling.","If yes, put it in a paper bag first.","If not, add it to compost or use as pet bedding."]],
["Paper cups","Kitchen","coffee cup, takeaway cup","Most paper cups have a thin plastic lining.",["Remove the plastic lid and recycle it separately if accepted.","Look for cup recycling bins at cafés and stations.","If there aren't any, put cups in the general bin."]],
["Drink cartons","Kitchen","juice carton, milk carton, tetra pak","Cartons mix paper, plastic and foil, but many areas can recycle them.",["Rinse and squash.","Put the cap back on.","Check if your local recycling accepts cartons."]],
["Plastic bags","Kitchen","carrier bag, shopping bag, film","Thin plastic bags jam sorting machines, so they need special collection.",["Keep bags clean and dry.","Bundle them together.","Take them to a supermarket collection point."]],
["Bubble wrap","Home","packing film, air cushions","Bubble wrap counts as soft plastic.",["Pop the bubbles if you like.","Keep it clean.","Drop at supermarket soft plastic points."]],
["Styrofoam","Home","polystyrene, foam, packing peanuts","Polystyrene is hard to recycle in most areas.",["Check for local foam collection points.","Ask shipping stores if they want packing peanuts.","If not accepted, put it in the general bin."]],
["Aerosol cans","Bathroom","deodorant spray, hairspray, spray paint","Empty aerosols are metal and can often be recycled.",["Use it until it's completely empty.","Don't pierce or crush it.","Put in your recycling with cans."]],
["Aluminum foil","Kitchen","tin foil, foil tray","Clean foil can be recycled.",["Wipe off food.","Scrunch into a ball bigger than a tennis ball.","Recycle with cans."]],
["AA batteries","Tech","battery, aaa, household battery","Batteries must never go in the bin, as they can cause fires.",["Keep used batteries in a jar.","Take them to a battery drop-off at supermarkets or libraries.","Tape the ends of larger batteries for safety."]],
["Lithium batteries","Tech","rechargeable battery, lithium ion","Lithium batteries can catch fire if crushed.",["Tape over the terminals.","Never put in household recycling.","Take to an electronics or battery drop-off point."]],
["Car batteries","Tech","lead acid battery","Car batteries are almost entirely recyclable.",["Handle carefully, as they contain acid.","Take to a garage or recycling center.","Many shops give you money back for them."]],
["Mobile phones","Tech","smartphone, cell phone","Phones contain gold, silver and copper.",["Back up and wipe your data.","Remove the SIM card.","Take to an e-waste drop-off or trade-in program."]],
["Laptops","Tech","computer, notebook","Laptops contain valuable metals.",["Back up and wipe data.","Remove the battery if possible.","Take to an electronics recycler."]],
["Televisions","Tech","tv, monitor, screen","TVs need special handling.",["Check if the retailer takes old ones back.","Book a bulky item collection.","Take to a recycling center."]],
["Incandescent bulbs","Tech","old light bulb","Old-style bulbs usually can't be recycled.",["Wrap in paper so it doesn't break.","Put in the general waste bin.","Replace with LED bulbs."]],
["Fluorescent bulbs","Tech","cfl, energy saving bulb, tube","These contain a little mercury.",["Handle carefully so it doesn't break.","Never put in the bin.","Take to a hazardous waste or bulb collection point."]],
["LED bulbs","Tech","led light","LEDs contain electronic parts.",["Keep the bulb intact.","Take to an electronics drop-off.","Many stores have bulb recycling boxes."]],
["Printer cartridges","Tech","ink cartridge, toner","Cartridges can be refilled or recycled.",["Put in the box your new one came in.","Use the manufacturer's free return scheme.","Drop off at office supply stores."]],
["CDs and DVDs","Tech","disc, cd, dvd","Discs are made of polycarbonate plastic.",["Remove paper inserts and recycle them.","Find a specialist disc recycler.","Don't put them in household recycling."]],
["Cables and chargers","Tech","cord, wire, usb","Cables contain copper that can be recovered.",["Bundle them together.","Take to an e-waste collection.","Never put in household recycling."]],
["Small appliances","Tech","toaster, kettle, hair dryer","Anything with a plug or battery is e-waste.",["Check if it can be repaired first.","Take to an electronics recycling point.","Some stores take them back when you buy new."]],
["Fridges","Home","refrigerator, freezer","Fridges contain gases that need safe removal.",["Ask the retailer to collect your old one.","Book a council bulky waste collection.","Never dump it."]],
["Microwaves","Home","microwave oven","Microwaves are e-waste.",["Clean it out.","Take to a recycling center.","Check if a retailer offers take-back."]],
["Paint cans","Home","paint tin, leftover paint","Leftover paint needs careful disposal.",["Donate usable paint to community projects.","Let small amounts dry out completely.","Take cans to a household waste site."]],
["Motor oil","Outdoors","engine oil, car oil","One liter of oil can pollute a million liters of water.",["Never pour it down the drain.","Store in a sealed container.","Take to a garage or recycling center."]],
["Tires","Outdoors","tyre, car tire","Tires can become playground surfaces.",["Leave them with the garage when you get new ones.","Take to a recycling center.","Never burn or dump them."]],
["Bicycles","Outdoors","bike, cycle","Bikes are mostly metal and very recyclable.",["Donate if it still works.","Take to a bike recycling project.","Scrap metal yards accept broken frames."]],
["Clothing","Wardrobe","clothes, textiles, fabric","Old clothes can be turned into insulation or new fibers.",["Donate wearable clothes.","Put worn-out textiles in a textile bank.","Keep them dry in a bag."]],
["Shoes","Wardrobe","sneakers, trainers, boots","Shoes can be recycled into sports surfaces.",["Tie pairs together.","Drop in a shoe bank.","Some sports shops take old trainers."]],
["Mattresses","Home","bed, mattress","Mattress springs and foam can be recovered.",["Check if the retailer collects old ones.","Book a bulky waste collection.","Find a specialist mattress recycler."]],
["Wooden furniture","Home","table, chair, wardrobe","Wood can be chipped and reused.",["Donate if it's usable.","Take to a recycling center's wood section.","Remove metal parts if possible."]],
["Scrap metal","Home","metal, iron, copper","Metal can be recycled endlessly.",["Separate different metals if you can.","Take to a scrap metal yard.","You might even get paid for it."]],
["Pots and pans","Kitchen","saucepan, frying pan, cookware","Metal cookware is recyclable as scrap.",["Donate if still usable.","Take to a scrap metal yard.","Don't put them in household recycling."]],
["Keys","Home","metal key","Keys are made of brass.",["Collect them in a jar.","Take to a scrap metal yard.","Some locksmiths collect them."]],
["Wire hangers","Wardrobe","coat hanger, metal hanger","Wire hangers jam recycling machines.",["Return to dry cleaners.","Take to scrap metal recycling.","Never put in household recycling."]],
["Plastic hangers","Wardrobe","coat hanger","Plastic hangers are rarely recyclable at home.",["Return to the shop.","Donate to charity shops.","Keep using them for years."]],
["Plastic toys","Home","toy, action figure","Toys are often made of mixed plastics.",["Donate if they still work.","Check for toy recycling programs.","Remove batteries first."]],
["Crayons","School & Office","wax crayon","Crayons can be melted into new ones.",["Collect broken crayons.","Send to a crayon recycling program.","Or melt them into new shapes at home."]],
["Pens and markers","School & Office","biro, felt tip, highlighter","Pens can be recycled through special schemes.",["Collect in a box at school.","Send to a writing instrument recycling program.","Don't put in household recycling."]],
["Eyeglasses","Wardrobe","glasses, spectacles, sunglasses","Glasses can help someone else see.",["Put in a protective case.","Drop at an optician collection box.","They'll be sent to people who need them."]],
["Mirrors","Home","mirror glass","Mirrors can't go in glass recycling.",["Donate if intact.","Wrap broken pieces carefully.","Take to a recycling center."]],
["Window glass","Home","glass pane, window","Window glass melts differently from bottles.",["Don't put it in bottle banks.","Take to a recycling center.","Wrap safely."]],
["Ceramics","Kitchen","mug, plate, china","Ceramics can't go in glass recycling.",["Donate if intact.","Use broken pieces for mosaics or drainage.","Put the rest in the general bin."]],
["Drinking glasses","Kitchen","tumbler, glass","Drinking glass melts at a different temperature from bottles.",["Donate if intact.","Wrap broken glass safely.","Put in the general bin, not glass recycling."]],
["Pyrex","Kitchen","ovenproof glass, baking dish","Heat-resistant glass can't be recycled with bottles.",["Donate if usable.","Wrap safely if broken.","Put in the general bin."]],
["Candle wax","Home","candle","Leftover wax can be remelted.",["Freeze the jar to pop out the wax.","Melt to make new candles.","Recycle the clean jar."]],
["Wine corks","Home","cork","Natural corks can be recycled.",["Collect corks in a bag.","Drop at a cork recycling point.","Or add natural cork to compost."]],
["Bottle caps","Kitchen","bottle top, metal cap","Metal caps are recyclable.",["Collect metal caps in a tin can.","Squeeze the can shut.","Recycle with cans."]],
["Plastic lids","Kitchen","tub lid, jar lid","Small lids can fall through sorting machines.",["Screw them onto bottles.","Check local rules for loose lids.","Collect in a bottle to keep them together."]],
["Yogurt cups","Kitchen","yoghurt pot, tub","Many yogurt cups are recyclable.",["Rinse clean.","Peel off the foil lid and recycle it separately.","Check the recycling number."]],
["Plastic clamshells","Kitchen","fruit punnet, berry container","Clear punnets are often recyclable.",["Remove absorbent pads.","Rinse.","Recycle if your area accepts them."]],
["Black plastic trays","Kitchen","ready meal tray, takeout tray","Black plastic is often invisible to sorting machines.",["Check if your area accepts it.","Wash it out.","If not, reuse or put in the general bin."]],
["Chip bags","Kitchen","crisp packet, snack bag","Chip bags are mixed materials.",["Look for special collection points.","Flatten and fold.","Otherwise put in the general bin."]],
["Candy wrappers","Kitchen","sweet wrapper, chocolate wrapper","Most candy wrappers aren't recyclable at home.",["Check for soft plastic collection points.","Foil wrappers can go in foil recycling.","Otherwise put in the general bin."]],
["Toothpaste tubes","Bathroom","toothpaste","Tubes need special recycling.",["Squeeze out as much as possible.","Look for newer recyclable tubes.","Use a specialist oral care recycling program."]],
["Toothbrushes","Bathroom","toothbrush","Plastic toothbrushes need special recycling.",["Clean them.","Use a toothbrush recycling program.","Bamboo handles can be composted after removing bristles."]],
["Contact lenses","Bathroom","lens, contacts","Lenses shouldn't be flushed.",["Collect used lenses and blister packs.","Drop at an optician recycling box.","Never flush them."]],
["Blister packs","Bathroom","pill packet, medicine packaging","Blister packs mix plastic and foil.",["Collect at pharmacies with recycling schemes.","Keep separate from other recycling.","Don't put in household bins."]],
["Medicines","Bathroom","pills, tablets, medication","Old medicine needs safe disposal.",["Never flush.","Take to a pharmacy.","Keep them in their packaging."]],
["Needles and sharps","Bathroom","syringe, sharps","Sharps must be handled carefully.",["Put in a sharps container.","Seal when full.","Return to a pharmacy or clinic."]],
["Food scraps","Kitchen","food waste, leftovers, peelings","Food waste can become compost or energy.",["Collect in a caddy.","Put in food waste collection or compost.","Avoid putting meat in home compost."]],
["Garden waste","Outdoors","yard waste, leaves, grass cuttings","Garden waste makes great compost.",["Collect leaves and cuttings.","Compost at home or use a garden waste bin.","Avoid adding diseased plants."]],
["Christmas trees","Outdoors","xmas tree, pine tree","Real trees can be chipped into mulch.",["Remove all decorations.","Take to a drop-off point.","Or cut up for garden waste."]],
["Coffee pods","Kitchen","coffee capsule, nespresso","Pods can be recycled through special schemes.",["Use the brand's recycling program.","Empty the grounds into compost.","Recycle aluminum pods with metals if accepted."]],
["Tea bags","Kitchen","teabag","Plastic-free tea bags can be composted.",["Check if your brand is plastic-free.","Compost plastic-free bags.","Otherwise split and compost the leaves."]],
["Egg cartons","Kitchen","egg box","Cardboard cartons are easy to recycle.",["Recycle cardboard ones with paper.","Plastic ones go with plastics.","Or compost cardboard ones."]],
["Receipts","School & Office","till receipt","Shiny receipts are coated with chemicals.",["Don't put them in paper recycling.","Put in the general bin.","Ask for email receipts next time."]],
["Wrapping paper","School & Office","gift wrap","Only plain paper wrap is recyclable.",["Do the scrunch test: if it springs back, it's not recyclable.","Remove tape and bows.","Recycle plain paper wrap."]],
["Glitter cards","School & Office","greeting card, birthday card","Glitter makes cards non-recyclable.",["Cut off glittery parts.","Recycle the plain parts.","Choose glitter-free next time."]],
["Window envelopes","School & Office","envelope, mail","Envelopes with windows can usually be recycled.",["Check local rules.","Remove plastic windows if needed.","Recycle with paper."]],
["Books","School & Office","novel, textbook","Books are recyclable, but donating is better.",["Donate readable books.","Remove hard covers before recycling.","Recycle the paper pages."]],
["Sticky notes","School & Office","post it","Sticky notes can be recycled with paper.",["Collect them together.","Recycle with paper.","Avoid ones with plastic coatings."]],
["Tissue boxes","Bathroom","tissue box","Tissue boxes are recyclable cardboard.",["Remove the plastic film.","Flatten the box.","Recycle with cardboard."]],
["Paper towels","Kitchen","kitchen roll, napkin","Used paper towels can't be recycled.",["Compost clean or food-stained ones.","Put greasy or chemical ones in the bin.","Switch to cloths."]],
["Nappies","Bathroom","diapers","Disposable nappies can't be recycled at home.",["Put in the general bin.","Look for specialist schemes.","Consider cloth nappies."]],
["Cooking oil","Kitchen","frying oil, vegetable oil","Used oil can become biofuel.",["Let it cool.","Store in a sealed bottle.","Take to a recycling center."]],
["Propane tanks","Outdoors","gas bottle, camping gas","Gas bottles must be returned.",["Return to the supplier.","Never put in bins.","Take to a household waste site."]],
["Fire extinguishers","Home","extinguisher","Extinguishers need specialist disposal.",["Contact a fire safety company.","Take to a household waste site.","Don't put in bins."]],
["Smoke detectors","Home","smoke alarm","Some detectors contain radioactive material.",["Remove the battery.","Return to the manufacturer.","Take to a household waste site."]],
["Mercury thermometers","Bathroom","thermometer","Mercury is toxic.",["Keep it sealed.","Take to hazardous waste collection.","Never throw in the bin."]],
["Solar panels","Tech","solar","Solar panels contain glass and metals.",["Contact the installer.","Use a specialist recycler.","Don't break the glass."]],
["E-bike batteries","Tech","ebike battery, scooter battery","These batteries are large and powerful.",["Return to the retailer.","Use a battery recycling center.","Never put in bins."]],
["Vapes","Tech","e-cigarette, disposable vape","Vapes have batteries inside.",["Never put in the bin.","Return to shops that sell them.","Use battery recycling points."]],
["Hair dryers","Tech","hairdryer, straighteners","Hair tools are e-waste.",["Check if it can be repaired.","Take to an electronics recycler.","Remove any batteries."]],
["Rubber bands","School & Office","elastic band","Rubber bands aren't recyclable at home.",["Keep reusing them.","Give spares to post offices.","Put broken ones in the general bin."]],
["Detergent bottles","Home","laundry bottle, cleaning bottle, bleach bottle","Sturdy household bottles are usually made from easy-to-recycle plastic.",["Use every last drop, then rinse with a little water.","Put the cap back on.","Recycle with your household plastics."]],
["Cereal boxes","Kitchen","cereal packet, food box","The box is recyclable card, but the bag inside usually isn't.",["Take out the inner bag and check if it can go to soft plastic collection.","Flatten the box.","Recycle the box with cardboard."]],
["Paper bags","Kitchen","brown bag, shopping bag","Paper bags recycle easily, as long as they're clean and dry.",["Reuse them a few times first.","Remove any plastic handles.","Recycle with paper and cardboard."]],
["Umbrellas","Home","brolly, broken umbrella","Umbrellas mix metal and fabric, so they need taking apart.",["Remove the fabric canopy.","Take the metal frame to scrap metal recycling.","Put fabric in a textile bank or reuse it."]]
];
